### ISSUE TITLE
load external resource like google webfonts

### ISSUE THREAD

**Issue by CanRau** [pyrsmk/toast#13] opened 2016-04-10 03:44 UTC
Hey, just wanted to load a google webfont using toast but it fails
Error
`Uncaught TypeError: Cannot read property '1' of null`
which refers to this line
`b=/(^.+\.\w+)(\?.*)?$/.exec(resource)[1];`

Normally I used [loadCSS from FilamentGroup](https://github.com/filamentgroup/loadCSS) but in this project I'm already using toast so why including two resource loaders..
I haven't actually looked into the source in this case and only tested with the webfont so maybe external sources are working in general..

Would love to use toast for loading the font asynchronously :+1: :D

Cheers

**Comment by pyrsmk** [comment] 2016-04-10 10:26
Toast was not designed to load other things than `js` or `css`, which is detecting by parsing the filename of the resource to load. It seems the error you got is a bug, it seems I didn't write this chunk of code properly. But! If you could load your fonts with toast before the update, that was a real bug, because toast shouldn't load anything else, by design.

I think I can find a way of specifying the type of the resource when toast cannot detect it (like a google font). Maybe : 

```js
toast('css:https://fonts.googleapis.com/css?family=Open+Sans');
```

**Comment by CanRau** [comment] 2016-04-10 13:45
I never tried it before, till now I only used toast to load a polyfill if modernizr says it's needed ;-)

That would be great :D

**Comment by pyrsmk** [comment] 2016-04-10 14:09
This is fixed with the upcoming release. You'll be able to update in 15 minutes ;)

**Closed by pyrsmk** 2016-04-10 14:09 UTC

**Comment by CanRau** [comment] 2016-04-10 14:49
Wow that was fast! Thank you :dancers:
